### ISSUE TITLE
Toteme Issue list

### ISSUE THREAD

**Issue by ahyun-park** [0sunman/toteme-korea-publish#135]
Demo text

- [x] to do list #01
- [x] to do list #02
- [x] to do list #03
